### ISSUE TITLE
Issue with grape - 0.15.0 

### ISSUE THREAD

**Issue by pbssubhash** [gottfrois/grape-attack#6]
Hey, 
Looks the newer version of grape is creating an issue with grape-attack 0.2.0. I recently ran 
`bundle update`
and it updated me to grape - 0.15.0 and I was getting the error 

```
NoMethodError in after callback inside Grape::Attack::Throttle : undefined method `[]=' for nil:NilClass
```

And eventually after about 2 hours, I figured it out and added version to `Gemfile` and ran 
`bundle update grape`. 

Everything is fine now but looks something is broken.

I'd be happy to share the trace and my Gemfile.lock.

Please look into this!

**Comment by gottfrois** [comment]
Yes, current implementation uses a "hack" to bypass an issue in grape 0.14. I need to look at the changes in 0.15 and adapt the code. In the meantime, you should probably stick with 0.14.

Thanks for reporting the issue.

**Comment by Freika** [comment]
Not fixed yet? Got the same error.

**Comment by Freika** [comment]
Full backtrace:

```
caught error of type NoMethodError in after callback inside Grape::Attack::Throttle : undefined method `[]=' for nil:NilClass

NoMethodError - undefined method `[]=' for nil:NilClass:
  grape-attack (0.2.0) lib/grape/attack/throttle.rb:20:in `after'
  grape (0.16.2) lib/grape/middleware/base.rb:33:in `ensure in call!'
  grape (0.16.2) lib/grape/middleware/base.rb:32:in `call!'
  grape (0.16.2) lib/grape/middleware/base.rb:23:in `call'
  grape (0.16.2) lib/grape/middleware/error.rb:29:in `block in call!'
  grape (0.16.2) lib/grape/middleware/error.rb:28:in `call!'
  grape (0.16.2) lib/grape/middleware/base.rb:23:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  grape (0.16.2) lib/grape/endpoint.rb:203:in `call!'
  grape (0.16.2) lib/grape/endpoint.rb:197:in `call'
  grape (0.16.2) lib/grape/router/route.rb:68:in `exec'
  grape (0.16.2) lib/grape/router.rb:63:in `block in identity'
  grape (0.16.2) lib/grape/router.rb:84:in `transaction'
  grape (0.16.2) lib/grape/router.rb:59:in `identity'
  grape (0.16.2) lib/grape/router.rb:44:in `block in call'
  grape (0.16.2) lib/grape/router.rb:107:in `with_optimization'
  grape (0.16.2) lib/grape/router.rb:43:in `call'
  grape (0.16.2) lib/grape/api.rb:112:in `call'
  grape (0.16.2) lib/grape/api.rb:45:in `call!'
  grape (0.16.2) lib/grape/api.rb:40:in `call'
  actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.6) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.6) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:9:in `<top (required)>'
  spring (1.7.1) lib/spring/client/rails.rb:28:in `call'
  spring (1.7.1) lib/spring/client/command.rb:7:in `call'
  spring (1.7.1) lib/spring/client.rb:30:in `run'
  spring (1.7.1) bin/spring:49:in `<top (required)>'
  spring (1.7.1) lib/spring/binstub.rb:11:in `<top (required)>'
  /Users/frey/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `<main>'
```

**Comment by gottfrois** [comment]
Should be fixed in `v0.3.0`

**Comment by Freika** [comment]
Awesome, thanks @gottfrois!

**Comment by pbssubhash** [comment]
Thanks :-)
